# This is my first, very own configuration file for yamllint!
# It extends the default conf by adjusting some options.

extends: default

ignore: |
  /helm/templates/

rules:
  document-start: disable
  line-length: disable
  truthy: disable
