apiVersion: apps/v1
kind: Deployment
metadata:
 name: express-sample
spec:
 replicas: 3
 selector:
   matchLabels:
     app: express-sample
 template:
   metadata:
     labels:
       app: express-sample
   spec:
     containers:
     - name: express-sample
       image: matamagu/express-sample
       resources:
          limits:
            memory: 128Mi
            cpu: 500m
       ports:
       - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: express-sample-svc
spec:
  selector:
    app: express-sample
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
