version: '3'

x-base: &base
  image: app
  # env_file:
  #   - ./.env
  environment:
    SSH_AUTH_SOCK: $SSH_AUTH_SOCK
  volumes:
    - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    - ./:/app
  tmpfs:
  - /tmp
  tty: true
  stdin_open: true
  # extra_hosts:

services:
  # app:
  #   <<: *base
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgresql
  #     - mongo

  postgresql:
    image: bitnami/postgresql:16.2.0
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  mysql:
    image: bitnami/mysql:8.0.36
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  # mariadb:
  #   image: bitnami/mariadb:11.1.4
  #   restart: unless-stopped
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes

  mongo:
    image: bitnami/mongodb:7.0.8
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=app_development

  kafka:
    image: bitnami/kafka:3.6.2
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
